### PR TITLE
Initial docker for easy deployments and testing

### PR DESCRIPTION
**Pull request by janabimustafa**
Please read the new README file and test to make sure the application runs. Leave comments if you would like things to change.

### CODE REVIEW

**Comment by azagon63** [comment]
<del>Should flask-launcher.sh also add --port=80, so we don't run on 5000? Unless we're going to handle the port redirect somewhere else.</del> Nevermind, I see we're doing that with traefik.

**Review by obits13 — APPROVED** [review]
Tested using Oracle VirtualBox. All's well. If using VirtualBox, http://localhost does not work.

**Comment by azagon63** [comment]
<del>Win10 Pro: docker-compose up -d works, but localhost:80 gets bad gateway. localhost:5000 gets the REST Api</del> http://localhost works and brings up the React homepage, but http://localhost/api fails because although an html doc is returned, the browser tries to fetch the pages at /swaggerui, which isn't available. Although, it seems like redirecting it to /api/swaggerui would be fine since that exists

**Review by hbkse — APPROVED** [review]
Works on win10 home with docker toolbox

**Comment by janabimustafa** [comment]
I added gunicorn with the --reload option so that your python changes will automatically reflect inside the docker container. I also added the CHOKIDAR_USEPOLLING=true flag to the npm launcher so that changes to the frontend react code will also reflect automatically. You will need to do 
```
docker-compose build 
```
then
```
docker-compose up -d
````
again for this update to reflect on your containers.

**Comment by janabimustafa** [comment]
Closed to test travis ci deployments

**Pull request merged**
