### PR TITLE
Changed GET parameters to path parameters.

### PR DESCRIPTION
**Pull request by azagon63**
Changed parameters from 'optional' arguments to path parameters, to make documentation easier and reduce code. Additionally, required arguments are typically part of the uri so that forgetting them results in a 404. Apiary assumes that true arguments (those after a ?) are optional.

### CODE REVIEW

**Comment by obits13** [comment]
I like it. The only thing I am concerned about right now is setting up the endpoint for players, since we have yet to discuss incorporating that into the site. We can leave it in and not document it until later on... thoughts?

**Review by obits13 — APPROVED** [review]

**Comment by azagon63** [comment]
I thought we had agreed on players because a leaderboard site had a REST Api, which we needed? Players are separate from everything else though, so I can see removing them; we would just need to find an additional source.

**Comment by obits13** [comment]
We have 3 sources. rocket-league.com, the RL wiki, and the rocketleaguestats for players. I didn't realize you added it to the report. I am concerned about adding models to the report that won't show up in the site. I am willing to leave it all in and just say that we are meeting the requirements for 4 models.

**Comment by azagon63** [comment]
Perhaps I am confused, but I was under the impression that we needed to scrape 2 _REST Api's_ not 2 _sources_. And the only reason we were looking at players was to fulfill that requirement. As far as I can tell, rocket-league.com doesn't have a REST Api?

**Comment by obits13** [comment]
I PMd you

**Pull request merged**
