### PR TITLE
Added db functionality to rest api. 

### PR DESCRIPTION
**Pull request by azagon63**
Although, it isn't connected to postgres for some reason. I think it has to do with the postgres port not being exposed. Even if it could connect, there's no data (or schema) in the database. I have a script to create them (SQLAlchemy make creating the schema really easy), but its mostly a one-and-done thing I think.

### CODE REVIEW

**Comment by azagon63** [comment]
There's still a few things to fix for functionality. I'd also like to enforce that ids are unique between multiple tables, but I don't know how to do that yet. I'll still have to add more tables for some of the relations between crates/dlc and items.

**Comment by janabimustafa** [comment]
The DB connection isn't done through the hostname "localhost". It is done through the hostname "db". I will amend the PR tomorrow, unless you want to do it.

**Comment by azagon63** [comment]
Ah, I figured it out; I was a bit confused because when trying to reach the api through localhost:80/api on my browser, I get redirected to flask:5000/api. It makes sense that the hostnames are defined in the containers, but the redirect outside is pretty weird. On another note, I'm not sure if there's a better way to secure access to the db than just having a password and not opening the port? Let me know your thoughts

**Comment by azagon63** [comment]
Alright, fixed that and can confirm it connects to postgres. However, on just starting the docker image, the only role is the default (postgres). Would it be possible to add another role and create the rldb database when building the image? I can create the schema (see comment in db_definitions.py), then import scraped data after, but it wont be permanent.

**Comment by janabimustafa** [comment]
Hey, I changed it a bit so the db info is coming from environmental variables instead of being hard-coded. I also made it so the db has the new role. You will need to remove the old db container using 
``
docker stop rldb-db && docker rm rldb-db
``
then you can resume the normal workflow again

**Pull request merged**
